#!/bin/sh --
set -ex
SCRIPT_DIR="$(cd -- "${0%/*}/" && pwd)"
. "$SCRIPT_DIR/../hc/tools/shell/recipe.sh"

DEPENDENCIES="host_llvm linux"
DIR_DEPENDENCIES="../hc ../bootloader"

recipe_start
export NO_AARCH64=1 LLVM="$OUT/host_llvm" FLAGS="-I$OUT/linux"
"$SCRIPT_DIR/../hc/tools/build/efi.sh" "$SCRIPT_DIR/../bootloader/bootloader.c" bootloader .efi
mv "$SCRIPT_DIR/../hc-out/bootloader/x86_64" .
recipe_finish
