#!/bin/sh --
set -ex
SCRIPT_DIR="$(cd -- "${0%/*}/" && pwd)"
. "$SCRIPT_DIR/../hc/tools/shell/recipe.sh"

DEPENDENCIES="hc linux"
DIR_DEPENDENCIES="../bootloader"

recipe_start
export LLVM="$OUT/host_llvm"
export ARCH=x86_64
export ABI=windows-gnu
export FLAGS="-Wl,-subsystem,efi_application -Os -s -I $OUT/linux"
export FLAGS_RELEASE= FLAGS_DEBUG=
OUT="$OUT/$SCRIPT_NAME" "$SCRIPT_DIR/../hc/tools/builder.sh" "$SCRIPT_DIR/../bootloader/bootloader.efi.c"
recipe_finish
