#!/bin/sh --
set -ex
SCRIPT_DIR="$(cd -- "${0%/*}/" && pwd)"
. "$SCRIPT_DIR/../hc/src/shell/recipe.sh"

. "$SCRIPT_DIR/files/urls"

DEPENDENCIES="hc llvm_x86_64 musl_x86_64 coreutils_x86_64 bash_x86_64 gzip_x86_64 tar_x86_64 sed_x86_64 diffutils_x86_64 findutils_x86_64 grep_x86_64 mawk_x86_64"

recipe_start
mkdir bin
cp "$OUT/llvm_x86_64/bin/clang-16" bin/clang
cp "$OUT/llvm_x86_64/bin/lld" bin/ld.lld
cp "$OUT/llvm_x86_64/bin/llvm-ar" bin/ar
cp "$OUT/coreutils_x86_64/bin/coreutils" bin/
cp "$OUT/bash_x86_64/bin/bash" bin/sh
cp "$OUT/gzip_x86_64/gzip" bin/
cp "$OUT/tar_x86_64/bin/tar" bin/
cp "$OUT/sed_x86_64/bin/sed" bin/
cp "$OUT/diffutils_x86_64/bin/diff" bin/
cp "$OUT/diffutils_x86_64/bin/cmp" bin/
cp "$OUT/findutils_x86_64/bin/find" bin/
cp "$OUT/findutils_x86_64/bin/xargs" bin/
cp "$OUT/grep_x86_64/bin/grep" bin/
cp "$OUT/mawk_x86_64/bin/mawk" bin/awk

mkdir lib
cp "$OUT/musl_x86_64/lib/Scrt1.o" lib/
cp "$OUT/musl_x86_64/lib/crti.o" lib/
cp "$OUT/musl_x86_64/lib/crtn.o" lib/
cp "$OUT/musl_x86_64/lib/libc.so" lib/
cp "$OUT/musl_x86_64/lib/libdl.a" lib/
cp "$OUT/musl_x86_64/lib/libm.a" lib/
cp "$OUT/musl_x86_64/lib/libpthread.a" lib/
cp "$OUT/musl_x86_64/lib/librt.a" lib/

echo '#!/bin/sh --' > bin/true
echo '#!/bin/sh --
echo "$@"' > bin/echo
echo '#!/bin/sh --
printf "$@"' > bin/printf
echo '#!/bin/sh --
test "$@"' > bin/test
cat > bin/cc <<"end"
#!/bin/sh --
case "$0" in
    */*)
    script_dir="${0%/*}"
    ;;
    *)
    IFS=:
    for script_dir in $PATH; do
        test -f "$script_dir/$0" && break
    done
    unset IFS
    ;;
esac
sysroot="$(cd -- "$script_dir/.." && pwd)"
end
cp bin/cc bin/c++
cp bin/cc bin/cpp
cp bin/cc bin/ld
cp bin/cc bin/ldd
setup_coreutils_wrappers() {
    for prog in "$@"; do
        cp bin/cc "bin/$prog"

        echo 'exec "$sysroot/bin/coreutils" --coreutils-prog="'$prog'" "$@"' >> "bin/$prog"
    done
}
setup_coreutils_wrappers basename cat chmod comm cp cut date dirname env expr head ln ls mkdir mv nl rm rmdir sha512sum sleep sort tail tee touch tr uname uniq wc
cp bin/cc bin/install
echo 'exec "$sysroot/bin/coreutils" --coreutils-prog=ginstall "$@"' >> bin/install
echo 'exec "$sysroot/bin/clang" -Wno-unused-command-line-argument -Wl,-dynamic-linker="$sysroot/lib/libc.so" "$@"' >> bin/cc
echo 'exec "$sysroot/bin/clang" --driver-mode=g++ -Wno-unused-command-line-argument -Wl,-dynamic-linker="$sysroot/lib/libc.so" "$@"' >> bin/c++
echo 'exec "$sysroot/bin/clang" --driver-mode=cpp "$@"' >> bin/cpp
echo 'exec "$sysroot/bin/ld.lld" "$@"' >> bin/ld
echo 'exec "$sysroot/lib/libc.so" --list "$@"' >> bin/ldd

"$OUT/hc/tar" \
-o devtools.tar \
-d devtools -p devtools \
-d bin -d lib -d include \
-p devtools/bin \
-a ./bin \
-p devtools/lib \
-a "$OUT/llvm/lib" \
-a "$OUT/llvm_x86_64/lib" \
-a ./lib \
-p devtools/include \
-a "$OUT/llvm_x86_64/include" \
-a "$OUT/musl_x86_64/include"


rm -rf ./bin
recipe_finish
