#!/bin/sh --
set -ex
SCRIPT_DIR="$(cd -- "${0%/*}/" && pwd)"
. "$SCRIPT_DIR/../hc/src/shell/recipe.sh"

. "$SCRIPT_DIR/files/urls"

DEPENDENCIES="hc llvm_x86_64 musl_x86_64 coreutils_x86_64 bash_x86_64 gzip_x86_64 tar_x86_64 sed_x86_64 diffutils_x86_64 findutils_x86_64 grep_x86_64 mawk_x86_64 utilities_x86_64"

recipe_start
mkdir bin
cp "$OUT/llvm_x86_64/bin/clang-16" bin/clang
cp "$OUT/llvm_x86_64/bin/lld" bin/ld.lld
cp "$OUT/llvm_x86_64/bin/llvm-ar" bin/ar
cp "$OUT/coreutils_x86_64/bin/coreutils" bin/
cp "$OUT/bash_x86_64/bin/bash" bin/sh
cp "$OUT/gzip_x86_64/gzip" bin/
cp "$OUT/tar_x86_64/bin/tar" bin/
cp "$OUT/sed_x86_64/bin/sed" bin/
cp "$OUT/diffutils_x86_64/bin/diff" bin/
cp "$OUT/diffutils_x86_64/bin/cmp" bin/
cp "$OUT/findutils_x86_64/bin/find" bin/
cp "$OUT/findutils_x86_64/bin/xargs" bin/
cp "$OUT/grep_x86_64/bin/grep" bin/
cp "$OUT/mawk_x86_64/bin/mawk" bin/awk

mkdir lib
cp "$OUT/musl_x86_64/lib/Scrt1.o" lib/
cp "$OUT/musl_x86_64/lib/crti.o" lib/
cp "$OUT/musl_x86_64/lib/crtn.o" lib/
cp "$OUT/musl_x86_64/lib/libc.so" lib/
cp "$OUT/musl_x86_64/lib/libdl.a" lib/
cp "$OUT/musl_x86_64/lib/libm.a" lib/
cp "$OUT/musl_x86_64/lib/libpthread.a" lib/
cp "$OUT/musl_x86_64/lib/librt.a" lib/

setup_sh_wrappers() {
    for prog in "$@"; do
        cp "$OUT/utilities_x86_64/x86_64-linux_shWrapper" "bin/$prog"
    done
}
setup_coreutils_wrappers() {
    for prog in "$@"; do
        cp "$OUT/utilities_x86_64/x86_64-linux_coreutilsWrapper" "bin/$prog"
    done
}
setup_clang_wrappers() {
    for prog in "$@"; do
        cp "$OUT/utilities_x86_64/x86_64-linux_clangWrapper" "bin/$prog"
    done
}
setup_clang_compiler_wrappers() {
    for prog in "$@"; do
        cp "$OUT/utilities_x86_64/x86_64-linux_clangCompilerWrapper" "bin/$prog"
    done
}
setup_lld_wrappers() {
    for prog in "$@"; do
        cp "$OUT/utilities_x86_64/x86_64-linux_lldWrapper" "bin/$prog"
    done
}
setup_libc_so_wrappers() {
    for prog in "$@"; do
        cp "$OUT/utilities_x86_64/x86_64-linux_libcSoWrapper" "bin/$prog"
    done
}
setup_sh_wrappers echo false printf test true 
setup_coreutils_wrappers basename cat chmod comm cp cut date dd dirname env expr head install ln ls mkdir mv nl rm rmdir sha512sum sleep sort tail tee touch tr uname uniq wc
setup_clang_wrappers cpp
setup_clang_compiler_wrappers cc c++
setup_lld_wrappers ld
setup_libc_so_wrappers ldd

recipe_finish
