#!/bin/sh --
set -ex
SCRIPT_DIR="$(cd -- "${0%/*}/" && pwd)"
. "$SCRIPT_DIR/../hc/src/shell/recipe.sh"

. "$SCRIPT_DIR/files/urls"
sha512="219d2c815a120690c6589846271e43aee5c96c61a7ee4abbef97dfcdb3d6416652ed494b417de0ab6688c4322540d48be63b5e617beb6d20530b5d55d723ccbb"

DEPENDENCIES="make xz llvm musl_x86_64"

recipe_start
export PATH="$OUT/make/bin:$OUT/xz/bin:$OUT/llvm/bin:$PATH"
xz -d -c "$(recipe_download "$url_diffutils" "$sha512")" | tar xf -
cd ./diffutils-3.10

arch=x86_64
export CC=clang AR=llvm-ar
export CFLAGS="-target $arch-unknown-linux-musl --sysroot $OUT/musl_$arch -Os -ffunction-sections -fno-asynchronous-unwind-tables"
export CPPFLAGS="-target $arch-unknown-linux-musl --sysroot $OUT/musl_$arch"
export LDFLAGS="-target $arch-unknown-linux-musl --sysroot $OUT/musl_$arch -static -Wl,--gc-sections"
# https://savannah.gnu.org/support/?110846
sed -e 's/cross_compiling=maybe/cross_compiling=yes/' ./configure > ./sed.temp
mv ./sed.temp ./configure
chmod +x ./configure
./configure ac_cv_path_PR_PROGRAM="" --prefix= --host=$arch-unknown-linux-musl --disable-dependency-tracking --disable-threads --disable-rpath --disable-nls --without-libsigsegv-prefix --without-libiconv-prefix --without-libintl-prefix

make -j "$NUM_CPUS" install DESTDIR="$OUT/$SCRIPT_NAME"
llvm-objcopy --strip-sections "$OUT/$SCRIPT_NAME/bin/diff"
llvm-objcopy --strip-sections "$OUT/$SCRIPT_NAME/bin/cmp"

rm -rf "$PWD"
recipe_finish
