#!/bin/sh --
set -ex
SCRIPT_DIR="$(cd -- "${0%/*}/" && pwd)"
. "$SCRIPT_DIR/../hc/tools/shell/recipe.sh"

. "$SCRIPT_DIR/files/urls"
sha512="1e8e70b362d64a233591906a1f50b59001db04ca14aaffad522198b04680be501736e7d536b4191e2f99767e7001ca486cd802362cca2be05d5d409b83ea732d"

DEPENDENCIES="make xz llvm musl_x86_64"

recipe_start
export PATH="$OUT/make/bin:$OUT/xz/bin:$OUT/llvm/bin:$PATH"
xz -d -c "$(recipe_download "$url_zlib" "$sha512")" | tar xf -
cd ./zlib-1.3.1

arch=x86_64
export CC=clang AR=llvm-ar RANLIB=true NM=false
export CFLAGS="-target $arch-unknown-linux-musl --sysroot $OUT/musl_$arch -Os -ffunction-sections -fno-asynchronous-unwind-tables"
export LDFLAGS="-target $arch-unknown-linux-musl --sysroot $OUT/musl_$arch -static -Wl,--gc-sections"
./configure --prefix= --uname=Linux --static

make -j "$NUM_CPUS" all64
mv ./minigzip64 "$OUT/$SCRIPT_NAME/gzip"
llvm-objcopy --strip-sections "$OUT/$SCRIPT_NAME/gzip"
touch -t 197001010000.00 "$OUT/$SCRIPT_NAME/gzip"

rm -rf "$PWD"
recipe_finish
