#!/bin/sh --
set -ex
SCRIPT_DIR="$(cd -- "${0%/*}/" && pwd)"
. "$SCRIPT_DIR/../hc/src/shell/recipe.sh"

DEPENDENCIES="llvm"
DIR_DEPENDENCIES="../hc"

recipe_start
export LLVM="$OUT/llvm"
OUT="$OUT/$SCRIPT_NAME" "$SCRIPT_DIR/../hc/tools/tar/hostbuild.sh"
recipe_finish
