#!/bin/sh --
set -eax
SCRIPT_DIR="$(cd -- "${0%/*}/" && pwd)"
. "$SCRIPT_DIR/../hc/tools/shell/recipe.sh"
recipe_init "../hc/bootstrap/make host_m4"

pkg="flex-2.6.4"
URL="https://github.com/westes/flex/releases/download/v2.6.4/$pkg.tar.gz"
SHA512="e9785f3d620a204b7d20222888917dc065c2036cae28667065bf7862dfa1b25235095a12fd04efdbd09bfd17d3452e6b9ef953a8c1137862ff671c97132a082e"

recipe_start
export PATH="$PWD/make-out/bin:$PWD/host_m4-out/bin:$PATH"
rm -rf "./$pkg"; gzip -d -c "$DOWNLOAD" | tar xf -; cd "./$pkg"

# https://github.com/westes/flex/issues/428
./configure --prefix="$RECIPE_OUT" --disable-dependency-tracking --disable-nls --disable-libfl --without-libiconv-prefix --without-libintl-prefix CFLAGS="-g -O2 -D_GNU_SOURCE"
make -j "$NUM_CPUS" install

cd ..; rm -rf "./$pkg"
recipe_finish
