#!/bin/sh --
set -ex
SCRIPT_DIR="$(cd -- "${0%/*}/" && pwd)"
. "$SCRIPT_DIR/../hc/tools/shell/recipe.sh"

pkg="hostapd-2.10"
url="https://w1.fi/releases/$pkg.tar.gz"
sha512="243baa82d621f859d2507d8d5beb0ebda15a75548a62451dc9bca42717dcc8607adac49b354919a41d8257d16d07ac7268203a79750db0cfb34b51f80ff1ce8f"

DEPENDENCIES="../hc/bootstrap/make host_llvm musl libnl3"
DIR_DEPENDENCIES="files/hostapd"

recipe_start
export PATH="$OUT/make/bin:$OUT/host_llvm/bin:$PATH"
gzip -d -c "$(recipe_download "$url" "$sha512")" | tar xf -
cd "./$pkg"

cp "$SCRIPT_DIR/files/hostapd/.config" hostapd/
arch=x86_64
export CC=clang
export CFLAGS="-target $arch-unknown-linux-musl --sysroot $OUT/musl/$arch -I$OUT/linux-headers/$arch"
export LDFLAGS="-target $arch-unknown-linux-musl --sysroot $OUT/musl/$arch -static -L$OUT/libnl3/lib"
make -C hostapd -j "$NUM_CPUS" install BINDIR= DESTDIR="$OUT/$SCRIPT_NAME" LIBNL_INC="$OUT/libnl3/include/libnl3"
llvm-objcopy --strip-sections "$OUT/$SCRIPT_NAME/hostapd"

rm -rf "$PWD"
recipe_finish
