#!/bin/sh --
set -ex
SCRIPT_DIR="$(cd -- "${0%/*}/" && pwd)"
. "$SCRIPT_DIR/../hc/tools/shell/recipe.sh"

DEPENDENCIES="hc"
DIR_DEPENDENCIES="../init"

recipe_start
export LLVM="$OUT/llvm"
export ARCH=x86_64
export ABI=linux
export FLAGS="-Os"
export FLAGS_RELEASE= FLAGS_DEBUG=
OUT="$OUT/$SCRIPT_NAME" "$SCRIPT_DIR/../hc/tools/builder.sh" "$SCRIPT_DIR/../init/init.c"
"$SCRIPT_DIR/../hc/objcopy.sh" --strip-sections "$OUT/$SCRIPT_NAME/$ARCH-${ABI}_init"
touch -t 197001010000.00 "$OUT/$SCRIPT_NAME/$ARCH-${ABI}_init"
touch -t 197001010000.00 "$OUT/$SCRIPT_NAME/debug_$ARCH-${ABI}_init"
recipe_finish
