#!/bin/sh --
set -eax
SCRIPT_DIR="$(cd -- "${0%/*}/" && pwd)"
. "$SCRIPT_DIR/../hc/tools/shell/recipe.sh"

DEPENDENCIES="host_llvm"
FILE_DEPENDENCIES=""
URL=""
SHA512=""

recipe_start
export NO_AARCH64=1 NO_RISCV64=1 LLVM="$PWD/host_llvm-out"
"$SCRIPT_DIR/../hc/tools/build/elf.sh" "$SCRIPT_DIR/../init/init.c" init
mkdir "$RECIPE_OUT"
mv "$SCRIPT_DIR/../hc-out/init/x86_64" "$RECIPE_OUT/"

FILE_DEPENDENCIES="$(cd "$SCRIPT_DIR"; "$LLVM/bin/clang" -I../hc/src -M ../init/init.c)"
FILE_DEPENDENCIES="$(echo "${FILE_DEPENDENCIES#*:}" | sed 's/\\//g')"
recipe_finish
