#!/bin/sh --
set -eax
SCRIPT_DIR="$(cd -- "${0%/*}/" && pwd)"
. "$SCRIPT_DIR/../hc/tools/shell/recipe.sh"

pkg="libnl-3.8.0"
DEPENDENCIES="../hc/bootstrap/make host_llvm host_bison host_flex musl linux-headers"
FILE_DEPENDENCIES=""
URL="https://github.com/thom311/libnl/releases/download/libnl3_8_0/$pkg.tar.gz"
SHA512="a8da7e8464c5cab2807cd86f83fca53bc77f7c3bdefe43880db7be9caf5ba6bfca1b7e778b906c12fda1cf7e6f413f88cc7ad1dcc42fe8c050a8d28a6e656c02"

recipe_start
musl_out="$PWD/musl-out"
linux_headers_out="$PWD/linux-headers-out"
export PATH="$PWD/make-out/bin:$PWD/host_llvm-out/bin:$PWD/host_bison-out/bin:$PWD/host_flex-out/bin:$PATH"
rm -rf "./$pkg"; gzip -d -c "$DOWNLOAD" | tar xf -; cd "./$pkg"

arch=x86_64
export CC=clang AR=llvm-ar RANLIB=llvm-ranlib
export CFLAGS="-target $arch-unknown-linux-musl --sysroot $musl_out/$arch -I$linux_headers_out/$arch"
./configure --prefix= --host=$arch --disable-dependency-tracking --disable-debug --enable-shared=no
make -j "$NUM_CPUS" install DESTDIR="$RECIPE_OUT"

cd ..; rm -rf "./$pkg"
recipe_finish
