#!/bin/sh --
set -ex
SCRIPT_DIR="$(cd -- "${0%/*}/" && pwd)"
. "$SCRIPT_DIR/../hc/tools/shell/recipe.sh"

pkg="linux-6.6"
url="https://www.kernel.org/pub/linux/kernel/v6.x/$pkg.tar.xz"
sha512="458b2c34d46206f9b4ccbac54cc57aeca1eaecaf831bc441e59701bac6eadffc17f6ce24af6eadd0454964e843186539ac0d63295ad2cc32d112b60360c39a35"

DEPENDENCIES="../hc/bootstrap/make ../hc/bootstrap/xz"

recipe_start
export PATH="$OUT/make/bin:$OUT/xz/bin:$PATH"
xz -d -c "$(recipe_download "$url" "$sha512")" | tar xf -
cd "./$pkg"

export ARCH=x86_64
make -j "$NUM_CPUS" headers HOSTCC="$CC"
cd ./usr/include
test -z "$(find . -type f -name "*.h" ! -exec /bin/sh -c 'set -e; dest="$1/$2"; mkdir -p "${dest%/*}/"; cp "$2" "$dest"' sh "$OUT/$SCRIPT_NAME/$ARCH" {} \; -print)"
cd ../..

rm -rf "$PWD"
recipe_finish
