#!/bin/sh --
set -ex
SCRIPT_DIR="$(cd -- "${0%/*}/" && pwd)"
. "$SCRIPT_DIR/../hc/tools/shell/recipe.sh"

. "$SCRIPT_DIR/files/urls"
sha512="458b2c34d46206f9b4ccbac54cc57aeca1eaecaf831bc441e59701bac6eadffc17f6ce24af6eadd0454964e843186539ac0d63295ad2cc32d112b60360c39a35"

DEPENDENCIES="make xz hc bc flex bison elfutils perl linux-firmware wireless-regdb init router utilities hostapd_x86_64"
DIR_DEPENDENCIES="files/linux"

recipe_start
export PATH="$OUT/make/bin:$OUT/xz/bin:$OUT/llvm/bin:$OUT/bc/bin:$OUT/flex/bin:$OUT/bison/bin:$OUT/perl/bin:$PATH"
xz -d -c "$(recipe_download "$url_linux" "$sha512")" | tar xf -
cd ./linux-6.6

export KBUILD_BUILD_TIMESTAMP="1970-01-01" KBUILD_BUILD_USER="@" KBUILD_BUILD_HOST="@" ARCH=x86_64
export HOSTCFLAGS="-I$OUT/elfutils/include" HOSTLDFLAGS="-Wl,-rpath,$OUT/elfutils/lib -L$OUT/elfutils/lib"
tools="CC=clang LD=ld.lld AR=llvm-ar NM=llvm-nm STRIP=llvm-strip OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump READELF=llvm-readelf PAHOLE=false"
cp "$SCRIPT_DIR/files/linux/.config" .

make -j "$NUM_CPUS" -C ./usr gen_init_cpio CC="$CC"

# Build release image.
export DEBUG_PREFIX=
./usr/gen_init_cpio -t 0 "$SCRIPT_DIR/files/linux/initramfs" > ./initramfs.cpio
make -j "$NUM_CPUS" $tools HOSTCC="$CC"
mv arch/x86/boot/bzImage "$OUT/$SCRIPT_NAME/"

# Build debug image.
export DEBUG_PREFIX=debug_
./usr/gen_init_cpio -t 0 "$SCRIPT_DIR/files/linux/initramfs" > ./initramfs.cpio
make -j "$NUM_CPUS" $tools HOSTCC="$CC"
mv arch/x86/boot/bzImage "$OUT/$SCRIPT_NAME/debug_bzImage"

rm -rf "$PWD"
recipe_finish
