#!/bin/sh --
set -ex
SCRIPT_DIR="$(cd -- "${0%/*}/" && pwd)"
. "$SCRIPT_DIR/../hc/tools/shell/recipe.sh"

pkg="linux-firmware-20230625"
url="https://www.kernel.org/pub/linux/kernel/firmware/$pkg.tar.xz"
sha512="0e48aa7f63495485426d37491c7cb61843165625bd47f912c5d83628c6de871759f1a78be3af3d651f7c396bd87dff07e21ba7afc47896c1c143106d5f16d351"

DEPENDENCIES="../hc/bootstrap/xz"

recipe_start
"$OUT/xz/bin/xz" -d -c "$(recipe_download "$url" "$sha512")" | tar xf - "$pkg/iwlwifi-cc-a0-77.ucode"
mv "./$pkg" bin
recipe_finish
