#!/bin/sh --
set -ex
SCRIPT_DIR="$(cd -- "${0%/*}/" && pwd)"
. "$SCRIPT_DIR/../hc/tools/shell/recipe.sh"

. "$SCRIPT_DIR/files/urls"
sha512="498ec5d7941194a8806f4d42f0f6d218c862996ef1398b737d0d06995e0b7a6574b240a48088f6b84016b14b2776fe463f829dcb11149cdfc1023d496b235c55"

DEPENDENCIES="make host_llvm"

recipe_start
export PATH="$OUT/make/bin:$OUT/host_llvm/bin:$PATH"
gzip -d -c "$(recipe_download "$url_musl" "$sha512")" | tar xf -
cd ./musl-1.2.4

arch=x86_64
export CC=clang AR=llvm-ar RANLIB=llvm-ranlib
export CFLAGS="-target $arch-unknown-linux-musl"
export LIBCC="$("$CC" $CFLAGS --print-libgcc-file-name)"
./configure --prefix= --target=$arch
make -j "$NUM_CPUS" install DESTDIR="$OUT/$SCRIPT_NAME/$arch"

rm -rf "$PWD"
recipe_finish
