#!/bin/sh --
set -eax
SCRIPT_DIR="$(cd -- "${0%/*}/" && pwd)"
. "$SCRIPT_DIR/../hc/tools/shell/recipe.sh"

pkg="musl-1.2.4"
DEPENDENCIES="../hc/bootstrap/make"
FILE_DEPENDENCIES=""
URL="https://musl.libc.org/releases/$pkg.tar.gz"
SHA512="498ec5d7941194a8806f4d42f0f6d218c862996ef1398b737d0d06995e0b7a6574b240a48088f6b84016b14b2776fe463f829dcb11149cdfc1023d496b235c55"

recipe_start
export PATH="$PWD/make-out/bin:$PATH"
rm -rf "./$pkg"; gzip -d -c "$DOWNLOAD" | tar xf -; cd "./$pkg"

arch=x86_64
make -j "$NUM_CPUS" install-headers ARCH=$arch prefix= DESTDIR="$RECIPE_OUT/$arch"

cd ..; rm -rf "./$pkg"
recipe_finish
