#!/bin/sh --
set -ex
SCRIPT_DIR="$(cd -- "${0%/*}/" && pwd)"
. "$SCRIPT_DIR/../hc/tools/shell/recipe.sh"

DEPENDENCIES="host_llvm"
DIR_DEPENDENCIES="../hc ../router"

recipe_start
export NO_AARCH64=1 NO_RISCV64=1 LLVM="$OUT/host_llvm"
"$SCRIPT_DIR/../hc/tools/build/elf.sh" "$SCRIPT_DIR/../router/router.c" router
mv "$SCRIPT_DIR/../hc-out/router/x86_64" .
recipe_finish
