#!/bin/sh --
set -ex
SCRIPT_DIR="$(cd -- "${0%/*}/" && pwd)"
. "$SCRIPT_DIR/../hc/src/shell/recipe.sh"

. "$SCRIPT_DIR/files/urls"
sha512="36157a4b4a2430cf421b7bd07f1675d680d9f1616be96cf6ad6ee74a9ec0fe695f8d0b1e1f0b008bbb33cc7fcde5e1c456359bbbc63f8aebdd4fedc3982cf6dc"

DEPENDENCIES="make xz llvm musl_x86_64"

recipe_start
export PATH="$OUT/make/bin:$OUT/xz/bin:$OUT/llvm/bin:$PATH"
xz -d -c "$(recipe_download "$url_sed" "$sha512")" | tar xf -
cd ./sed-4.9

arch=x86_64
export CC=clang AR=llvm-ar
export CFLAGS="-target $arch-unknown-linux-musl --sysroot $OUT/musl_$arch -Os -ffunction-sections -fno-asynchronous-unwind-tables"
export CPPFLAGS="-target $arch-unknown-linux-musl --sysroot $OUT/musl_$arch"
export LDFLAGS="-target $arch-unknown-linux-musl --sysroot $OUT/musl_$arch -static -Wl,--gc-sections"
# https://savannah.gnu.org/support/?110846
sed -e 's/cross_compiling=maybe/cross_compiling=yes/' ./configure > ./sed.temp
mv ./sed.temp ./configure
chmod +x ./configure
./configure --prefix= --host=$arch-unknown-linux-musl --disable-dependency-tracking --disable-threads --disable-acl --disable-nls --disable-rpath --disable-i18n --without-selinux --without-libiconv-prefix --without-libintl-prefix >/dev/null

make -j "$NUM_CPUS" install DESTDIR="$OUT/$SCRIPT_NAME" >/dev/null
llvm-objcopy --strip-sections "$OUT/$SCRIPT_NAME/bin/sed"

rm -rf "$PWD"
recipe_finish
