#!/bin/sh --
set -ex
SCRIPT_DIR="$(cd -- "${0%/*}/" && pwd)"
. "$SCRIPT_DIR/../hc/src/shell/recipe.sh"

DEPENDENCIES="hc"
DIR_DEPENDENCIES=".."

recipe_start
"$OUT/hc/tar" \
-o source.tar \
-d source -p source \
-a "$SCRIPT_DIR/.."
recipe_finish
