#!/bin/sh --
set -ex
SCRIPT_DIR="$(cd -- "${0%/*}/" && pwd)"
. "$SCRIPT_DIR/../hc/src/shell/recipe.sh"

DEPENDENCIES="hc"
DIR_DEPENDENCIES="../utilities"

recipe_start
export LLVM="$OUT/llvm"
export ARCH=x86_64
export ABI=linux
export FLAGS="-Werror -Os"
export FLAGS_RELEASE= FLAGS_DEBUG=

OUT="$OUT/$SCRIPT_NAME" "$SCRIPT_DIR/../hc/tools/builder.sh" "$SCRIPT_DIR/../utilities/env.c"
"$SCRIPT_DIR/../hc/objcopy.sh" --strip-sections "$OUT/$SCRIPT_NAME/$ARCH-${ABI}_env"
touch -t 197001010000.00 "$OUT/$SCRIPT_NAME/$ARCH-${ABI}_env"
touch -t 197001010000.00 "$OUT/$SCRIPT_NAME/debug_$ARCH-${ABI}_env"

OUT="$OUT/$SCRIPT_NAME" "$SCRIPT_DIR/../hc/tools/builder.sh" "$SCRIPT_DIR/../utilities/mount.c"
"$SCRIPT_DIR/../hc/objcopy.sh" --strip-sections "$OUT/$SCRIPT_NAME/$ARCH-${ABI}_mount"
touch -t 197001010000.00 "$OUT/$SCRIPT_NAME/$ARCH-${ABI}_mount"
touch -t 197001010000.00 "$OUT/$SCRIPT_NAME/debug_$ARCH-${ABI}_mount"

OUT="$OUT/$SCRIPT_NAME" "$SCRIPT_DIR/../hc/tools/builder.sh" "$SCRIPT_DIR/../utilities/shell.c"
"$SCRIPT_DIR/../hc/objcopy.sh" --strip-sections "$OUT/$SCRIPT_NAME/$ARCH-${ABI}_shell"
touch -t 197001010000.00 "$OUT/$SCRIPT_NAME/$ARCH-${ABI}_shell"
touch -t 197001010000.00 "$OUT/$SCRIPT_NAME/debug_$ARCH-${ABI}_shell"

echo '#!/usr/bin/env sh
exec sh "$@"
' > "$OUT/$SCRIPT_NAME/sh"
touch -t 197001010000.00 "$OUT/$SCRIPT_NAME/sh"
recipe_finish
