#!/bin/sh --
set -eax
SCRIPT_DIR="$(cd -- "${0%/*}/" && pwd)"
. "$SCRIPT_DIR/../hc/tools/shell/recipe.sh"

pkg="wireless-regdb-2023.09.01"
DEPENDENCIES="../hc/bootstrap/xz"
FILE_DEPENDENCIES=""
URL="https://www.kernel.org/pub/software/network/wireless-regdb/$pkg.tar.xz"
SHA512="e88b4ea8b40f916f4e6c7fea8ea1b9fc7c6ece755d6ce24a8f43f66840f68e9971938707b0d94c87a2aa00dfe7f5734df469e0e088a82fe544a031b1d7422596"

recipe_start
rm -rf "./$pkg"; "$PWD/xz-out/bin/xz" -d -c "$DOWNLOAD" | tar xf - "$pkg/regulatory.db"
mv "./$pkg" "$RECIPE_OUT"
recipe_finish
