#!/bin/sh --
set -ex
SCRIPT_DIR="$(cd -- "${0%/*}/" && pwd)"
. "$SCRIPT_DIR/../hc/tools/shell/recipe.sh"

. "$SCRIPT_DIR/files/urls"
sha512="1e8e70b362d64a233591906a1f50b59001db04ca14aaffad522198b04680be501736e7d536b4191e2f99767e7001ca486cd802362cca2be05d5d409b83ea732d"

DEPENDENCIES="make xz"

recipe_start
export PATH="$OUT/make/bin:$OUT/xz/bin:$PATH"
xz -d -c "$(recipe_download "$url_zlib" "$sha512")" | tar xf -
cd ./zlib-1.3.1

./configure --prefix=
make -j "$NUM_CPUS" install DESTDIR="$OUT/$SCRIPT_NAME"

rm -rf "$PWD"
recipe_finish
