#include "hc/hc.h"
hc_EXPORT void __libc_start_main(void) {}
hc_EXPORT void __cxa_atexit(void) {}
hc_EXPORT void __errno_location(void) {}
hc_EXPORT void printf(void) {}
hc_EXPORT void clock_gettime(void) {}
hc_EXPORT void getauxval(void) {}
hc_EXPORT void memfd_create(void) {}
hc_EXPORT void ftruncate(void) {}
hc_EXPORT void mmap(void) {}
hc_EXPORT void munmap(void) {}
hc_EXPORT void socket(void) {}
hc_EXPORT void connect(void) {}
hc_EXPORT void sendmsg(void) {}
hc_EXPORT void sendto(void) {}
hc_EXPORT void recvfrom(void) {}
hc_EXPORT void writev(void) {}
hc_EXPORT void close(void) {}
hc_EXPORT void openat(void) {}
hc_EXPORT void fstatat(void) {}
hc_EXPORT void ioctl(void) {}
hc_EXPORT void read(void) {}
hc_EXPORT void ppoll(void) {}
