#!/bin/sh --
set -ex
SCRIPT_DIR="$(cd -- "${0%/*}/" && pwd)"
. "$SCRIPT_DIR/../hc/tools/shell/recipe.sh"

. "$SCRIPT_DIR/files/urls"

recipe_start
mkdir out
cd ./out
cp "$(recipe_download "$url_e2fsprogs" "2ac51f7654a44adf3ee5a5e32cecd7f129e423bdf3074c60b22a7acdba131e7dd0bb2964c107a06ae133f51836272be166f5da1f996f67ceb6c22e2636117beb")" .
touch -t 197001010000.00 e2fsprogs-1.47.1.tar.xz
recipe_finish
