#!/bin/sh --
set -ex
SCRIPT_DIR="$(cd -- "${0%/*}/" && pwd)"
. "$SCRIPT_DIR/../hc/src/shell/recipe.sh"

. "$SCRIPT_DIR/files/urls"
sha512="2ac51f7654a44adf3ee5a5e32cecd7f129e423bdf3074c60b22a7acdba131e7dd0bb2964c107a06ae133f51836272be166f5da1f996f67ceb6c22e2636117beb"

DEPENDENCIES="../recipes/make ../recipes/xz"

recipe_start
export PATH="$OUT/make/bin:$OUT/xz/bin:$PATH"
xz -d -c "$(recipe_download "$url_e2fsprogs" "$sha512")" | tar xf -
cd ./e2fsprogs-1.47.1

# https://www.spinics.net/lists/linux-ext4/msg95502.html
sed -e 's/#define llseek lseek/#define my_llseek lseek/' lib/blkid/llseek.c > sed.temp
mv sed.temp lib/blkid/llseek.c

./configure --prefix="$OUT/$SCRIPT_NAME" --disable-testio-debug --disable-backtrace --disable-debugfs --disable-imager --disable-resizer --disable-defrag --disable-uuidd --disable-mmp --disable-tdb --disable-bmap-stats --disable-nls --disable-rpath --disable-fuse2fs --without-libiconv-prefix --without-libintl-prefix --without-libarchive --with-udev-rules-dir=no --with-crond-dir=no --with-systemd-unit-dir=no
make -j "$NUM_CPUS" install E2SCRUB_DIR=

rm -rf "$PWD"
recipe_finish
