#!/bin/sh --
set -ex
SCRIPT_DIR="$(cd -- "${0%/*}/" && pwd)"
. "$SCRIPT_DIR/../hc/src/shell/recipe.sh"

DIR_DEPENDENCIES="../utilities ../hc"

recipe_start
mkdir "$OUT/$SCRIPT_NAME/bin"
export ARCH="$(uname -m)"
export ABI="linux"
"$SCRIPT_DIR/../hc/cc.sh" -Os -s -o "$OUT/$SCRIPT_NAME/bin/setsid" "$SCRIPT_DIR/../utilities/setsid.c"
recipe_finish
