#!/bin/sh --
set -ex
SCRIPT_DIR="$(cd -- "${0%/*}/" && pwd)"
. "$SCRIPT_DIR/../src/shell/recipe.sh"

pkg="cmake-3.27.1"
url="https://github.com/Kitware/CMake/releases/download/v3.27.1/$pkg.tar.gz"
sha512="d8831105fed3772bcb821a2b184fe0ffbff15795a5b0a89f2ad1cb0372a40c8f22f2bab72c671a6d17464521b7337067df929a5c3ece99f84848cc3a2fe6716f"

DEPENDENCIES="make"

recipe_start
export PATH="$OUT/make/bin:$PATH"
gzip -d -c "$(recipe_download "$url" "$sha512")" | tar xf -
cd "./$pkg"

./bootstrap --prefix="$OUT/$SCRIPT_NAME" --no-debugger --parallel="$NUM_CPUS" --generator="Unix Makefiles" -- -DCMAKE_USE_OPENSSL=OFF
make -j "$NUM_CPUS" install

rm -rf "$PWD"
recipe_finish
