#!/bin/sh --
set -ex
SCRIPT_DIR="$(cd -- "${0%/*}/" && pwd)"
. "$SCRIPT_DIR/../tools/shell/recipe.sh"

pkg="Python-3.11.4"
url="https://www.python.org/ftp/python/3.11.4/$pkg.tar.xz"
sha512="7eb14fecbf60824d10c22a9057584c3a142c2866f4af6caa2525c10c8bcb24e6e7afb32a44a0e118df0a2b2543d578c3b422ffd4a5fa317dfe6ea371cc7ee1ee"

DEPENDENCIES="make xz"

recipe_start
export PATH="$OUT/make/bin:$OUT/xz/bin:$PATH"
xz -d -c "$(recipe_download "$url" "$sha512")" | tar xf -
cd "./$pkg"

./configure --prefix="$OUT/$SCRIPT_NAME" --without-ensurepip
make -j "$NUM_CPUS" install

rm -rf "$PWD"
recipe_finish
