#!/bin/sh --
set -ex
SCRIPT_DIR="$(cd -- "${0%/*}/" && pwd)"
. "$SCRIPT_DIR/../../hc/src/shell/recipe.sh"

. "$SCRIPT_DIR/../files/urls"
sha512="86c484428b8805768fd580d0f62aa32ce8f588f4beedcdd35a4014506b562928c7a2fa6487aa0d853b4c9c1639a4d186f46b4e96721568ff81191d5098403ca8"

DEPENDENCIES="../make ../xz ncurses"

recipe_start
export PATH="$OUT/make/bin:$OUT/xz/bin:$PATH"
xz -d -c "$(recipe_download "$url_nano" "$sha512")" | tar xf -
cd ./nano-8.0

export CFLAGS="-I$OUT/ncurses/include"
export LDFLAGS="-L$OUT/ncurses/lib"
./configure --prefix="$OUT/$SCRIPT_NAME" --disable-dependency-tracking --disable-nls --disable-utf8 --without-libiconv-prefix --without-libintl-prefix
make -j "$NUM_CPUS" install

mkdir "$OUT/$SCRIPT_NAME/etc"
echo "include $OUT/$SCRIPT_NAME/share/nano/*.nanorc" > "$OUT/$SCRIPT_NAME/etc/nanorc"

rm -rf "$PWD"
recipe_finish
