static uint32_t (*gl_getError)(void);
static void (*gl_clear)(uint32_t mask);
static void (*gl_clearColor)(float red, float green, float blue, float alpha);
static void (*gl_viewport)(int32_t x, int32_t y, int32_t width, int32_t height);
static void (*gl_genBuffers)(int32_t n, uint32_t *buffers);
static void (*gl_bindBuffer)(uint32_t target, uint32_t buffer);
static void (*gl_bufferData)(uint32_t target, int64_t size, const void *data, uint32_t usage);
static uint32_t (*gl_createShader)(uint32_t type);
static void (*gl_shaderSource)(uint32_t shader, int32_t count, const char *const *string, const int32_t *length);
static void (*gl_compileShader)(uint32_t shader);
static uint32_t (*gl_createProgram)(void);
static void (*gl_attachShader)(uint32_t program, uint32_t shader);
static void (*gl_linkProgram)(uint32_t program);
static void (*gl_useProgram)(uint32_t program);
static void (*gl_deleteProgram)(uint32_t program);
static void (*gl_deleteShader)(uint32_t shader);
static void (*gl_vertexAttribPointer)(uint32_t index, int32_t size, uint32_t type, uint8_t normalized, int32_t stride, const void *pointer);
static void (*gl_enableVertexAttribArray)(uint32_t index);
static void (*gl_genVertexArrays)(int32_t n, uint32_t *arrays);
static void (*gl_bindVertexArray)(uint32_t array);
static void (*gl_deleteVertexArrays)(int32_t n, uint32_t *arrays);
static void (*gl_deleteBuffers)(int32_t n, uint32_t *buffers);
static void (*gl_drawElementsInstanced)(uint32_t mode, int32_t count, uint32_t type, const void *indices, int32_t primcount);
static void (*gl_vertexAttribDivisor)(uint32_t index, uint32_t divisor);
static void (*gl_uniformMatrix4fv)(int32_t location, int32_t count, uint8_t transpose, const float *value);
static int32_t (*gl_getUniformLocation)(uint32_t program, const char *name);

static int32_t gl_init(struct wgl *wgl) {
    if ((gl_getError = wgl_getProcAddress(wgl, "glGetError")) == NULL) return -1;
    if ((gl_clear = wgl_getProcAddress(wgl, "glClear")) == NULL) return -1;
    if ((gl_clearColor = wgl_getProcAddress(wgl, "glClearColor")) == NULL) return -1;
    if ((gl_viewport = wgl_getProcAddress(wgl, "glViewport")) == NULL) return -1;
    if ((gl_genBuffers = wgl_getProcAddress(wgl, "glGenBuffers")) == NULL) return -1;
    if ((gl_bindBuffer = wgl_getProcAddress(wgl, "glBindBuffer")) == NULL) return -1;
    if ((gl_bufferData = wgl_getProcAddress(wgl, "glBufferData")) == NULL) return -1;
    if ((gl_createShader = wgl_getProcAddress(wgl, "glCreateShader")) == NULL) return -1;
    if ((gl_shaderSource = wgl_getProcAddress(wgl, "glShaderSource")) == NULL) return -1;
    if ((gl_compileShader = wgl_getProcAddress(wgl, "glCompileShader")) == NULL) return -1;
    if ((gl_createProgram = wgl_getProcAddress(wgl, "glCreateProgram")) == NULL) return -1;
    if ((gl_attachShader = wgl_getProcAddress(wgl, "glAttachShader")) == NULL) return -1;
    if ((gl_linkProgram = wgl_getProcAddress(wgl, "glLinkProgram")) == NULL) return -1;
    if ((gl_useProgram = wgl_getProcAddress(wgl, "glUseProgram")) == NULL) return -1;
    if ((gl_deleteProgram = wgl_getProcAddress(wgl, "glDeleteProgram")) == NULL) return -1;
    if ((gl_deleteShader = wgl_getProcAddress(wgl, "glDeleteShader")) == NULL) return -1;
    if ((gl_vertexAttribPointer = wgl_getProcAddress(wgl, "glVertexAttribPointer")) == NULL) return -1;
    if ((gl_enableVertexAttribArray = wgl_getProcAddress(wgl, "glEnableVertexAttribArray")) == NULL) return -1;
    if ((gl_genVertexArrays = wgl_getProcAddress(wgl, "glGenVertexArrays")) == NULL) return -1;
    if ((gl_bindVertexArray = wgl_getProcAddress(wgl, "glBindVertexArray")) == NULL) return -1;
    if ((gl_deleteVertexArrays = wgl_getProcAddress(wgl, "glDeleteVertexArrays")) == NULL) return -1;
    if ((gl_deleteBuffers = wgl_getProcAddress(wgl, "glDeleteBuffers")) == NULL) return -1;
    if ((gl_drawElementsInstanced = wgl_getProcAddress(wgl, "glDrawElementsInstanced")) == NULL) return -1;
    if ((gl_vertexAttribDivisor = wgl_getProcAddress(wgl, "glVertexAttribDivisor")) == NULL) return -1;
    if ((gl_uniformMatrix4fv = wgl_getProcAddress(wgl, "glUniformMatrix4fv")) == NULL) return -1;
    if ((gl_getUniformLocation = wgl_getProcAddress(wgl, "glGetUniformLocation")) == NULL) return -1;
    return 0;
}